codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 15%
    patch:
      default:
        target: 80%
        threshold: 15%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches:
    - "master"
